-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 13:28:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- ãããin ãããin uuh uh
-- -----------------------------------------------------
-- Schema Escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Escola` ;

-- -----------------------------------------------------
-- Schema Escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escola` DEFAULT CHARACTER SET utf8 ;
USE `Escola` ;

-- -----------------------------------------------------
-- Table `Escola`.`TipoLogradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`TipoLogradouro` ;

CREATE TABLE IF NOT EXISTS `Escola`.`TipoLogradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Pais` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Estado` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `fk_pais` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_pais`)
    REFERENCES `Escola`.`Pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Localidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Localidade` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Localidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `fk_estado` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_estado`)
    REFERENCES `Escola`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `fk_cidade` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_cidade`)
    REFERENCES `Escola`.`Localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Logradouro` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Logradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_bairro` INT NOT NULL,
  `fk_tipo_logradouro` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_tipo_logradouro`)
    REFERENCES `Escola`.`TipoLogradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_bairro`)
    REFERENCES `Escola`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_logradouro` INT NOT NULL,
  `numero` INT NOT NULL,
  `cep` CHAR(9) NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_logradouro`)
    REFERENCES `Escola`.`Logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Usuário` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sobrenome` VARCHAR(80) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` INT NOT NULL,
  `cpf` INT(11) NOT NULL,
  `fk_endereco` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `data_entrada` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_endereco`)
    REFERENCES `Escola`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Curso` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `fk_departamento` INT NOT NULL,
  `ppc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `fk_curso` INT NOT NULL,
  `fk_user` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`),
    FOREIGN KEY (`fk_user`)
    REFERENCES `Escola`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_curso`)
    REFERENCES `Escola`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_usuario`)
    REFERENCES `Escola`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Colegiado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Colegiado` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Colegiado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_curso` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_curso`)
    REFERENCES `Escola`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Professor` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_colegiado` INT NOT NULL,
  `fk_funcionario` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `Escola`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_colegiado`)
    REFERENCES `Escola`.`Colegiado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Permissao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`User-Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`User-Permissao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`User-Permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NOT NULL,
  `fk_permissao` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_user`)
    REFERENCES `Escola`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_permissao`)
    REFERENCES `Escola`.`Permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`NomeDisciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`NomeDisciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`NomeDisciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `NomeDisciplinacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` INT NOT NULL,
  `descricao` VARCHAR(240) NULL,
  `fk_curso` INT NOT NULL,
  `programa_desc` VARCHAR(500) NULL,
  `num_max_alunos` INT(7) NOT NULL,
  `carga_horaria` INT(10) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`nome`)
    REFERENCES `Escola`.`NomeDisciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_curso`)
    REFERENCES `Escola`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Semestre` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NULL,
  `semestre` INT(2) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`Disciplina-Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Disciplina-Semestre` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Disciplina-Semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_semestre` INT NOT NULL,
  `fk_disciplina` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_semestre`)
    REFERENCES `Escola`.`Semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_disciplina`)
    REFERENCES `Escola`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Aluno-Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Aluno-Disciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Aluno-Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_aluno` INT NOT NULL,
  `fk_disciplina_semestre` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_disciplina_semestre`)
    REFERENCES `Escola`.`Disciplina-Semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_aluno`)
    REFERENCES `Escola`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Aluno-Frequencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Aluno-Frequencia` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Aluno-Frequencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_aluno_disciplina` INT NOT NULL,
  `presenca` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_aluno_disciplina`)
    REFERENCES `Escola`.`Aluno-Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Professor-Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Professor-Disciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Professor-Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_professor` INT NOT NULL,
  `fk_disciplina-semestre` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_professor`)
    REFERENCES `Escola`.`Professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_disciplina-semestre`)
    REFERENCES `Escola`.`Disciplina-Semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Aluno-Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Aluno-Nota` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Aluno-Nota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_aluno_disciplina` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_aluno_disciplina`)
    REFERENCES `Escola`.`Aluno-Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_nivel_formacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_nivel_formacoes` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_nivel_formacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_nome_formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_nome_formacao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_nome_formacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_formacao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_formacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_funcionario` INT NOT NULL,
  `fk_nivel_formacao` INT NOT NULL,
  `fk_nome_formacao` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `Escola`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_nivel_formacao`)
    REFERENCES `Escola`.`tbl_nivel_formacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_nome_formacao`)
    REFERENCES `Escola`.`tbl_nome_formacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `Escola`.`Telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `fk_user` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_user`)
    REFERENCES `Escola`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_login` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `Escola`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

