-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 13:28:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- ãããin ãããin uuh uh
-- -----------------------------------------------------
-- Schema Escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Escola` ;

-- -----------------------------------------------------
-- Schema Escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escola` DEFAULT CHARACTER SET utf8 ;
USE `Escola` ;

-- -----------------------------------------------------
-- Table `Escola`.`tbl_TipoLogradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_TipoLogradouro` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_TipoLogradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Pais` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Estado` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `fk_pais` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_pais`)
    REFERENCES `Escola`.`tbl_Pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Localidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Localidade` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Localidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `fk_estado` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_estado`)
    REFERENCES `Escola`.`tbl_Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Bairro` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `fk_cidade` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_cidade`)
    REFERENCES `Escola`.`tbl_Localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Logradouro` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Logradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_bairro` INT NOT NULL,
  `fk_tipo_logradouro` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_tipo_logradouro`)
    REFERENCES `Escola`.`tbl_TipoLogradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_bairro`)
    REFERENCES `Escola`.`tbl_Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Endereco` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_logradouro` INT NOT NULL,
  `numero` INT NOT NULL,
  `cep` CHAR(9) NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_logradouro`)
    REFERENCES `Escola`.`tbl_Logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Usuário` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Usuário` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sobrenome` VARCHAR(80) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` INT NOT NULL,
  `cpf` INT(11) NOT NULL,
  `fk_endereco` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `data_entrada` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_endereco`)
    REFERENCES `Escola`.`tbl_Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Curso` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `fk_departamento` INT NOT NULL,
  `ppc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Aluno` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `fk_curso` INT NOT NULL,
  `fk_user` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`),
    FOREIGN KEY (`fk_user`)
    REFERENCES `Escola`.`tbl_Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_curso`)
    REFERENCES `Escola`.`tbl_Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Funcionario` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_usuario`)
    REFERENCES `Escola`.`tbl_Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Colegiado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Colegiado` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Colegiado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_curso` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_curso`)
    REFERENCES `Escola`.`tbl_Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Professor` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_colegiado` INT NOT NULL,
  `fk_funcionario` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `Escola`.`tbl_Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_colegiado`)
    REFERENCES `Escola`.`tbl_Colegiado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Permissao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_User-Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_User-Permissao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_User-Permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NOT NULL,
  `fk_permissao` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_user`)
    REFERENCES `Escola`.`tbl_Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_permissao`)
    REFERENCES `Escola`.`tbl_Permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_NomeDisciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_NomeDisciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_NomeDisciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `NomeDisciplinacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Disciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` INT NOT NULL,
  `descricao` VARCHAR(240) NULL,
  `fk_curso` INT NOT NULL,
  `programa_desc` VARCHAR(500) NULL,
  `num_max_alunos` INT(7) NOT NULL,
  `carga_horaria` INT(10) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`nome`)
    REFERENCES `Escola`.`tbl_NomeDisciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_curso`)
    REFERENCES `Escola`.`tbl_Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Semestre` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NULL,
  `semestre` INT(2) NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Disciplina-Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Disciplina-Semestre` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Disciplina-Semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_semestre` INT NOT NULL,
  `fk_disciplina` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_semestre`)
    REFERENCES `Escola`.`tbl_Semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_disciplina`)
    REFERENCES `Escola`.`tbl_Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Aluno-Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Aluno-Disciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Aluno-Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_aluno` INT NOT NULL,
  `fk_disciplina_semestre` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_disciplina_semestre`)
    REFERENCES `Escola`.`tbl_Disciplina-Semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_aluno`)
    REFERENCES `Escola`.`tbl_Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Aluno-Frequencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Aluno-Frequencia` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Aluno-Frequencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_aluno_disciplina` INT NOT NULL,
  `presenca` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_aluno_disciplina`)
    REFERENCES `Escola`.`tbl_Aluno-Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Professor-Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Professor-Disciplina` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Professor-Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_professor` INT NOT NULL,
  `fk_disciplina-semestre` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_professor`)
    REFERENCES `Escola`.`tbl_Professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_disciplina-semestre`)
    REFERENCES `Escola`.`tbl_Disciplina-Semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Aluno-Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Aluno-Nota` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Aluno-Nota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_aluno_disciplina` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_aluno_disciplina`)
    REFERENCES `Escola`.`tbl_Aluno-Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_nivel_formacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_nivel_formacoes` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_nivel_formacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_nome_formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_nome_formacao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_nome_formacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_formacao` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_formacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_funcionario` INT NOT NULL,
  `fk_nivel_formacao` INT NOT NULL,
  `fk_nome_formacao` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `Escola`.`tbl_Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_nivel_formacao`)
    REFERENCES `Escola`.`tbl_nivel_formacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`fk_nome_formacao`)
    REFERENCES `Escola`.`tbl_nome_formacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_Telefone` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_Telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `fk_user` INT NOT NULL,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`fk_user`)
    REFERENCES `Escola`.`tbl_Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Escola`.`tbl_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola`.`tbl_login` ;

CREATE TABLE IF NOT EXISTS `Escola`.`tbl_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `Escola`.`tbl_Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

